SELECT a.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    ROUND(AVG(REVIEW_SCORE),2) as SCORE
FROM REST_INFO a, REST_REVIEW b
WHERE a.REST_ID = b.REST_ID and
    ADDRESS LIKE '서울%'
GROUP BY a.REST_ID 
ORDER BY SCORE DESC, FAVORITES DESC

/*
주소 중간에 서울이 들어가는게 있나보다 
'%서울%'로 하면 틀림 

아래 코드처럼 RIGHT JOIN을 이용해도 됨! 
*/
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) SCORE 
FROM REST_INFO A RIGHT JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC